"""Adição de obeservação em NF e empenho

Revision ID: 1f8dfb2254a4
Revises: 44fff1e190f8
Create Date: 2025-11-09 19:58:07.052227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8dfb2254a4'
down_revision: Union[str, Sequence[str], None] = '44fff1e190f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empenho', sa.Column('observacao', sa.String(length=500), nullable=True))
    op.add_column('nota_fiscal', sa.Column('observacao', sa.String(length=500), nullable=True))
    op.add_column(
        "nota_fiscal", sa.Column("status_novo", sa.Enum("pendente", "em_ateste", "atestada", "liquidada", "cancelada", name="status_nota_fiscal_enum",), nullable=False, server_default="pendente",
        ),
    )

    op.execute(
        """
        UPDATE nota_fiscal
        SET status_novo = CASE status
            WHEN 'ativo' THEN 'pendente'
            WHEN 'inativo' THEN 'cancelada'
            ELSE 'pendente'
        END
        """
    )

    op.drop_column("nota_fiscal", "status")

    op.alter_column(
        "nota_fiscal",
        "status_novo",
        new_column_name="status",
        existing_type=sa.Enum(
            "pendente",
            "em_ateste",
            "atestada",
            "liquidada",
            "cancelada",
            name="status_nota_fiscal_enum",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nota_fiscal', 'observacao')
    op.drop_column('empenho', 'observacao')
    op.add_column(
        "nota_fiscal",
        sa.Column(
            "status_antigo",
            sa.Enum("ativo", "inativo", name="status_enum"),
            nullable=False,
            server_default="ativo",
        ),
    )

    op.execute(
        """
        UPDATE nota_fiscal
        SET status_antigo = CASE status
            WHEN 'pendente' THEN 'ativo'
            WHEN 'em_ateste' THEN 'ativo'
            WHEN 'atestada' THEN 'ativo'
            WHEN 'liquidada' THEN 'ativo'
            WHEN 'cancelada' THEN 'inativo'
            ELSE 'ativo'
        END
        """
    )

    op.drop_column("nota_fiscal", "status")

    op.alter_column(
        "nota_fiscal",
        "status_antigo",
        new_column_name="status",
        existing_type=sa.Enum("ativo", "inativo", name="status_enum"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
