"""Adição de ONDELETE CASCACADE as fks de item_empenho_id e item_ata_id

Revision ID: 44fff1e190f8
Revises: 8c3626289bb6
Create Date: 2025-10-11 10:11:30.792955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fff1e190f8'
down_revision: Union[str, Sequence[str], None] = '8c3626289bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_empenho_ibfk_1'), 'item_empenho', type_='foreignkey')
    op.create_foreign_key(None, 'item_empenho', 'item_ata', ['item_ata_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item_empenho', 'empenho', ['empenho_id'], ['id'])
    op.drop_constraint(op.f('item_nf_ibfk_2'), 'item_nf', type_='foreignkey')
    op.create_foreign_key(None, 'item_nf', 'item_empenho', ['item_empenho_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_nf', type_='foreignkey')
    op.create_foreign_key(op.f('item_nf_ibfk_2'), 'item_nf', 'item_empenho', ['item_empenho_id'], ['id'])
    op.drop_constraint(None, 'item_empenho', type_='foreignkey')
    op.drop_constraint(None, 'item_empenho', type_='foreignkey')
    op.create_foreign_key(op.f('item_empenho_ibfk_1'), 'item_empenho', 'item_ata', ['item_ata_id'], ['id'])
    # ### end Alembic commands ###
