"""Campo validade em ata

Revision ID: 56b30244c6db
Revises: 5450f1e839d0
Create Date: 2025-11-22 19:50:43.205749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b30244c6db'
down_revision: Union[str, Sequence[str], None] = '5450f1e839d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ata', sa.Column('validade', sa.Date(), nullable=True))
    op.execute("UPDATE ata SET validade = '2026-01-01'")
    op.alter_column('ata', 'validade', existing_type=sa.Date(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ata', 'validade')
    # ### end Alembic commands ###
