"""Remoção da coluna nivel_acesso de usuario

Revision ID: 7234e0d2aa7a
Revises: d02c7ecc1d2e
Create Date: 2025-10-09 09:52:41.838573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7234e0d2aa7a'
down_revision: Union[str, Sequence[str], None] = 'd02c7ecc1d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'nivel_acesso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nivel_acesso', mysql.ENUM('Superusuario', 'Admin', 'Editor', 'Leitor'), nullable=False))
    # ### end Alembic commands ###
