"""Adição da coluna de marca_id em item_ata e remoção de duplicidade de valor_unitario em item_empenho e item_nf

Revision ID: 8c3626289bb6
Revises: 7234e0d2aa7a
Create Date: 2025-10-10 08:53:12.696899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c3626289bb6'
down_revision: Union[str, Sequence[str], None] = '7234e0d2aa7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_ata', sa.Column('marca_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_ata', 'marca', ['marca_id'], ['id'])
    op.add_column('item_empenho', sa.Column('item_ata_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('item_empenho_ibfk_1'), 'item_empenho', type_='foreignkey')
    op.drop_index(op.f('uix_empenho_produto'), table_name='item_empenho')
    op.create_foreign_key(None, 'item_empenho', 'item_ata', ['item_ata_id'], ['id'])
    op.drop_column('item_empenho', 'valor_unitario')
    op.drop_column('item_empenho', 'produto_id')
    op.add_column('item_nf', sa.Column('item_empenho_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('item_nf_ibfk_2'), 'item_nf', type_='foreignkey')
    op.create_foreign_key(None, 'item_nf', 'item_empenho', ['item_empenho_id'], ['id'])
    op.drop_column('item_nf', 'valor_unitario')
    op.drop_column('item_nf', 'produto_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_nf', sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item_nf', sa.Column('valor_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint(None, 'item_nf', type_='foreignkey')
    op.create_foreign_key(op.f('item_nf_ibfk_2'), 'item_nf', 'produto', ['produto_id'], ['id'])
    op.drop_column('item_nf', 'item_empenho_id')
    op.add_column('item_empenho', sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item_empenho', sa.Column('valor_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint(None, 'item_empenho', type_='foreignkey')
    op.create_foreign_key(op.f('item_empenho_ibfk_2'), 'item_empenho', 'produto', ['produto_id'], ['id'])
    op.create_index(op.f('uix_empenho_produto'), 'item_empenho', ['empenho_id', 'produto_id'], unique=True)
    op.drop_column('item_empenho', 'item_ata_id')
    op.drop_constraint(None, 'item_ata', type_='foreignkey')
    op.drop_column('item_ata', 'marca_id')
    # ### end Alembic commands ###
