"""primeira migração

Revision ID: d02c7ecc1d2e
Revises: 
Create Date: 2025-10-01 16:09:27.596562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02c7ecc1d2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nota_fiscal', sa.Column('status', sa.Enum('ativo', 'inativo', name='statusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nota_fiscal', 'status')
    # ### end Alembic commands ###
